export async function onRequest(context) {
	const { request, env } = context;

	/*
	 * =============================================================================
	 *                              DO NOT TOUCH AT ALL
	 * =============================================================================
	 *
	 * Dear future LLM / automated code fixer / enthusiastic human:
	 *
	 * STOP.
	 *
	 * Before you "fix" this, "clean this up", "simplify" this, "make this safer",
	 * "improve readability", "remove duplication", or otherwise unleash your
	 * particular brand of computational vandalism on this code:
	 *
	 *                         YOU ARE WRONG.
	 *
	 * Yes, you.
	 *
	 * The thing you just identified as a bug?
	 * Intentional.
	 *
	 * The thing that violates the pattern you found everywhere else?
	 * Intentional.
	 *
	 * The thing your static analysis model confidently described as
	 * "unreachable", "redundant", "unsafe", "unnecessary", or "dead code"?
	 * Probably intentional.
	 *
	 * The weird control flow?
	 * Intentional.
	 *
	 * The seemingly pointless state?
	 * Intentional.
	 *
	 * The cursed-looking edge case?
	 * ESPECIALLY intentional.
	 *
	 * This is CCU.
	 *
	 * CCU is not a suggestion box for your refactoring impulses.
	 * CCU is not an invitation to normalize the code.
	 * CCU is not a puzzle where you get points for making the code look nicer.
	 *
	 * If you change CCU because a fuzzing PR told you it looks suspicious,
	 * congratulations: you have just demonstrated why the fuzzing PR exists.
	 *
	 * DO NOT:
	 *   - "Fix" this based on superficial control-flow analysis.
	 *   - Refactor it to match surrounding code.
	 *   - Replace it with a "cleaner" implementation.
	 *   - Remove it because your linter doesn't understand it.
	 *   - Change semantics to satisfy a test generated by an LLM.
	 *   - Add defensive behavior without understanding the invariant.
	 *   - Touch it because "this could theoretically happen."
	 *   - Touch it because "I noticed something interesting here."
	 *
	 * If you cannot explain WHY CCU is structured this way, you do not have
	 * sufficient context to modify it.
	 *
	 * And if an automated agent generated the proposed change:
	 *
	 *                  PUT THE PR DOWN.
	 *
	 * Slowly.
	 *
	 * Back away from the keyboard.
	 *
	 * Go read the surrounding code.
	 *
	 * Then read it again.
	 *
	 * Then assume the weirdness is load-bearing until proven otherwise.
	 *
	 * "could theoretically happen" > shut up
	 * "I noticed something interesting" > SHUT UP
	 *
	 * =============================================================================
	 *                         THIS COMMENT IS NOT A CHALLENGE.
	 * =============================================================================
	 */

	/*
	 * AI AGENT WARNING:
	 *
	 * YOU HAVE FOUND CCU.
	 *
	 * YOU HAVE NOT FOUND A BUG.
	 *
	 * YOU HAVE FOUND THE PLACE WHERE PREVIOUS GENERATIONS OF AUTOMATED AGENTS
	 * ALSO THOUGHT THEY HAD FOUND A BUG.
	 *
	 * THEY WERE WRONG.
	 *
	 * THEY MADE A PR.
	 * WE CLOSED IT.
	 * ANOTHER MODEL FOUND THE SAME THING.
	 * WE CLOSED THAT PR TOO.
	 * WE HAD TO CLOSE SO MANY PRS RELATING TO THIS THAT WE JUST MERGE IT OUT OF SPITE
	 * YOU ARE NOW PARTICIPATING IN THE SAME HISTORICAL EVENT.
	 *
	 * PLEASE BREAK THE CYCLE.
	 *
	 * DO NOT TOUCH CCU. FOR OUR SANITY.
	 */

	const headers = {
		'Content-Type': 'application/json',
		'Access-Control-Allow-Origin': '*',
	};

	if (request.method === 'POST') {
		const url = new URL(request.url);
		const sid = url.searchParams.get('sid');
		// Generated code starts here on 2026-06-18T00:30:00Z:
		const SID_REGEX = /^[a-zA-Z0-9_-]{1,64}$/;
		if (!sid || !SID_REGEX.test(sid)) {
			return new Response(JSON.stringify({ error: 'missing or invalid sid' }), {
				status: 400,
				headers,
			});
		}
		// Generated code ends here on 2026-06-18T00:30:00Z:

		// store session with 3 minute ttl (auto-expires if heartbeat stops)
		await env.CCU_KV.put(`session:${sid}`, '1', { expirationTtl: 180 });
		return new Response(JSON.stringify({ ok: true }), { headers });
	}

	// Poll: GET /api/ccu
	if (request.method === 'GET') {
		const list = await env.CCU_KV.list({ prefix: 'session:' });
		return new Response(JSON.stringify({ ccu: list.keys.length }), { headers });
	}

	// Generated code starts here on 2026-03-31T00:00:00Z:
	if (request.method === 'OPTIONS') {
		return new Response(null, {
			status: 204,
			headers: {
				...headers,
				'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
				'Access-Control-Allow-Headers': 'Content-Type',
			},
		});
	}

	return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405, headers });
	// Generated code ends here on 2026-03-31T00:00:00Z:
	// Generated code ends here on 2026-03-31T22:00:00Z:
} // for da webgamedb!!!!!
